version: '3.4'

services:
  sshd:
    build: .
    image: sshd
    container_name: sshd
    ports:
      - 0.0.0.0:8022:22/tcp
    volumes:
      - ./authorized_keys:/authorized_keys
    environment:
      CONNECTION_TIMEOUT: 5
