version: '3.4'

services:
  sshd:
    build: https://github.com/juanelas/singleuser-pkauth-sshd.git
    image: sshd
    container_name: sshd
    ports:
      - 8022:22/tcp
    volumes:
      - ./authorized_keys:/authorized_keys
      - ./ssh_hello.txt:/ssh_hello.txt
    environment:
      CONNECTION_TIMEOUT: 8
      SSH_HELLO_MSG: 'Yuhuuu'
